version: "2.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
    environment:
      - MONGO_URL=mongodb://mongo:27017/busTracker
  mongo:
    image: "mongo:4.0.11"
    ports:
      - "27017:27017"
    environment:
      - AUTH=no
  mongo_seed:
    image: "mongo:4.0.11"
    links:
      - mongo
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh
